# 服务端口
server:
  port: 9001
dubbo:
  application:
    name: web-center
  registry:
    address: 192.168.109.111:2181
    protocol: zookeeper
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  thymeleaf:
    cache: false

#上传文件
fdfs:
  so-timeout: 1500
  connect-timeout: 600
  pool:
    jmx-enabled: false
  thumb-image:
    width: 100
    height: 100
  tracker-list: 192.168.109.111:22122
#文件地址前缀
file:
  server: http://192.168.109.111/